server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: patientdatacollector
          uri: lb://SERVICE-PATIENTDATA
          predicates:
            - Path=/conjunta/2p/vital-signs/**
          filters:
            - StripPrefix=2
        - id: healthanalyzer
          uri: lb://SERVICE-HEALTHANALYZER
          predicates:
            - Path=/conjunta/2p/alerts/**
          filters:
            - StripPrefix=2
        - id: carenotifier
          uri: lb://SERVICE-CARENOTIFIER
          predicates:
            - Path=/conjunta/2p/mock/**
          filters:
            - StripPrefix=2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway